import type { DaggersData } from './product.d.ts'

const data: DaggersData = {
	"daggers": [
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With Extreme Carry Cuts, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-extreme-carry-cuts-sniper-green.html",
			"price": 299.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/5/1/51655129773_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-extreme-carry-cuts-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "none",
			"mag_bag_bonus": false,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol With Non Threaded Barrel, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-sw3-rmr-pistol-with-non-threaded-barrel-fde.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201576_12525_1.jpg",
			"image_file_name": "psa-dagger-compact-sw3-rmr-pistol-with-non-threaded-barrel-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol with SW1 RMR with Threaded Barrel & 10 17rd Mags & Bag, FDE (Rear Sight Rear)",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-sw1-rmr-with-threaded-barrel-ameriglo-lower-1-3-co-witness-10-17rd-mags-bag-fde-rear-sight-rear.html",
			"price": 449.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655132791_3926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-sw1-rmr-with-threaded-barrel-ameriglo-lower-1-3-co-witness-10-17rd-mags-bag-fde-rear-sight-rear.jpg",
			"size": "full_size_s",
			"width": 0,
			"length": 0,
			"height": 0,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": null,
			"slide_coating": "none",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 10,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Non Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-non-threaded-barrel-flat-dark-earth.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202181_21726_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-non-threaded-barrel-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-black.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202182_21726_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-flat-dark-earth.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202180_21326_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202179_21326_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel & 10-17rd Mags, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-10-17rd-mags-black.html",
			"price": 439.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202140_3926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-10-17rd-mags-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 10,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202128_2626_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With TiN Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-tin-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202129_2626_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-tin-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Chameleon Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-chameleon-threaded-barrel-black.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202146_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-chameleon-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Copper Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-copper-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202151_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-copper-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Non Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-non-threaded-barrel-black.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202143_2926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-non-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202142_2926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-flat-dark-earth2.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202163_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-flat-dark-earth2.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202162_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With TiN Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-tin-threaded-barrel-black.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202144_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-tin-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW6 RMR Pistol With Chameleon Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-chameleon-threaded-barrel-black.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202169_21326_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-chameleon-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": false,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW6 RMR Pistol With Non Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-non-threaded-barrel-black.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202168_21326_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-non-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.15,
			"height": 5.38,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": false,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW6 RMR Pistol With Threaded Barrel &10-17rd Mags, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-threaded-barrel-10-17rd-mags-flat-dark-earth.html",
			"price": 439.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202164_3926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-threaded-barrel-10-17rd-mags-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 10,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW6 RMR Pistol With Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-threaded-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202167_21326_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": false,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW6 RMR Pistol With Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202171_21326_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw6-rmr-pistol-with-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": false,
			"number_of_included_mags": 1,
			"mag_size": 17
		}
	],
	"slide_colors": {
		"sniper_green": "Sniper Green",
		"flat_dark_earth": "Flat Dark Earth",
		"black": "Black"
	},
	"frame_colors": {
		"sniper_green": "Sniper Green",
		"flat_dark_earth": "Flat Dark Earth",
		"black": "Black"
	}
} as const

export default data
