import type { DaggersData } from './product.d.ts'

const data: DaggersData = {
	"daggers": [
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol SWRV2 RMR With Non Threaded Stainless Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-swrv2-rmr-with-non-threaded-stainless-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202065_1826_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-swrv2-rmr-with-non-threaded-stainless-barrel-black.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol SWRV2 RMR With Threaded Chameleon Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-swrv2-rmr-with-threaded-chameleon-barrel-black.html",
			"price": 349.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202064_1826_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-swrv2-rmr-with-threaded-chameleon-barrel-black.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.9,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW2 ECC RMR Slide & Gold TiN Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw2-ecc-rmr-slide-gold-tin-threaded-barrel-sniper-green-rsf.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201569_12425_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw2-ecc-rmr-slide-gold-tin-threaded-barrel-sniper-green-rsf.jpg",
			"size": "compact",
			"width": 0,
			"length": 0,
			"height": 0,
			"barrel_length": 0,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": null,
			"slide_coating": "none",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW2 Extreme Carry Cut RMR Slide & Copper Threaded Barrel, w10-15rd mags, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw2-extreme-carry-cut-rmr-slide-copper-threaded-barrel-w10-15rd-mags-black.html",
			"price": 439.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201573_3926_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw2-extreme-carry-cut-rmr-slide-copper-threaded-barrel-w10-15rd-mags-black.jpg",
			"size": "compact",
			"width": 0,
			"length": 0,
			"height": 0,
			"barrel_length": 0,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": null,
			"slide_coating": "none",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW2 Extreme Carry Cut RMR Slide & Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw2-extreme-carry-cut-rmr-slide-threaded-barrel-sniper-green-rsf.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201568_12425_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw2-extreme-carry-cut-rmr-slide-threaded-barrel-sniper-green-rsf.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW3 ECC RMR Slide & Copper Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-copper-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201868_121025_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-copper-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW3 ECC RMR Slide & Gold TiN Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-gold-tin-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201867_121025_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-gold-tin-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW3 ECC RMR Slide & Non Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-non-threaded-barrel-sniper-green.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201866_121025_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-non-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_greencerakote",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW3 ECC RMR Slide & Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201754_121025_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw3-ecc-rmr-slide-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW4 ECC RMR Slide & Copper Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-copper-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202062_1626_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-copper-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW4 ECC RMR Slide & Gold TiN Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-gold-tin-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202019_1626_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-gold-tin-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW4 ECC RMR Slide & Non Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-non-threaded-barrel-sniper-green.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202018_1626_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-non-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW4 ECC RMR Slide & Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202017_1626_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw4-ecc-rmr-slide-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW4 Extreme Carry Cut RMR Slide & Copper Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw4-extreme-carry-cut-rmr-slide-copper-threaded-barrel-flat-dark-earth.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201970_123025_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw4-extreme-carry-cut-rmr-slide-copper-threaded-barrel-flat-dark-earth.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW4 Extreme Carry Cut RMR Slide & Non Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw4-extreme-carry-cut-rmr-slide-non-threaded-barrel-flat-dark-earth.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201978_123025_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw4-extreme-carry-cut-rmr-slide-non-threaded-barrel-flat-dark-earth.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SW4 Extreme Carry Cut RMR Slide & Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-sw4-extreme-carry-cut-rmr-slide-threaded-barrel-flat-dark-earth.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201969_123025_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-sw4-extreme-carry-cut-rmr-slide-threaded-barrel-flat-dark-earth.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SWRV2 RMR Slide & Copper Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-swrv2-rmr-slide-copper-threaded-barrel-flat-dark-earth.html",
			"price": 349.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202111_11526_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-swrv2-rmr-slide-copper-threaded-barrel-flat-dark-earth.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.9,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SWRV2 RMR Slide & Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-flat-dark-earth.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202108_11526_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-flat-dark-earth.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.9,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol With SWRV2 RMR Slide Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655202112_11526_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-sniper-green.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.9,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol W/Copper Spiral Fluted Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-sw3-rmr-pistol-w-copper-spiral-fluted-threaded-barrel-flat-dark-earth.html",
			"price": 359.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201577_122225_1.jpg",
			"image_file_name": "psa-dagger-compact-sw3-rmr-pistol-w-copper-spiral-fluted-threaded-barrel-flat-dark-earth.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol With Non Threaded Barrel, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-sw3-rmr-pistol-with-non-threaded-barrel-fde.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201576_12525_1.jpg",
			"image_file_name": "psa-dagger-compact-sw3-rmr-pistol-with-non-threaded-barrel-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol With Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-sw3-rmr-pistol-with-threaded-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201580_12925_1.jpg",
			"image_file_name": "psa-dagger-compact-sw3-rmr-pistol-with-threaded-barrel-black.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol With Threaded Barrel, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-sw3-rmr-pistol-with-threaded-barrel-fde.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201575_12525_1.jpg",
			"image_file_name": "psa-dagger-compact-sw3-rmr-pistol-with-threaded-barrel-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol With Threaded Barrel, w/10-15rd Mags, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-sw3-rmr-pistol-with-threaded-barrel-w-10-15rd-mags-fde.html",
			"price": 439.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201574_3926_1.jpg",
			"image_file_name": "psa-dagger-compact-sw3-rmr-pistol-with-threaded-barrel-w-10-15rd-mags-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 10,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW4 RMR Pistol With Chameleon Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-sw4-rmr-pistol-with-chameleon-threaded-barrel-black.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655201883_122925_1.jpg",
			"image_file_name": "psa-dagger-compact-sw4-rmr-pistol-with-chameleon-threaded-barrel-black.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.65,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW1 RMR Pistol, Threaded Barrel w/ 5 15rd & 5 27rd Mags, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-complete-sw1-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655210743_31926_1.jpg",
			"image_file_name": "psa-dagger-complete-sw1-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 5,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol, Threaded Barrel w/ 5 15rd & 5 27rd Mags, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-complete-sw3-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655210744_31926_1.jpg",
			"image_file_name": "psa-dagger-complete-sw3-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 5,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm ECC RMR Threaded Barrel Pistol, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-flat-dark-earth.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202121_13026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.15,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm ECC RMR Threaded Barrel Pistol, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-sniper-green.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202122_13026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.15,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol with SW1 RMR, Threaded Barrel & 5 17rd & 5 27rd Mags, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-sw1-rmr-threaded-barrel-5-15rd-5-17rd-mags-black.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655210745_31926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-sw1-rmr-threaded-barrel-5-15rd-5-17rd-mags-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black_cerkote",
			"slide_coating": "none",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 5,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol with SW2 RMR, Threaded Barrel & 5 17rd & 5 27rd Mags, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-sw2-rmr-threaded-barrel-5-15rd-5-17rd-mags-sniper-green.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655210746_31926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-sw2-rmr-threaded-barrel-5-15rd-5-17rd-mags-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": false,
			"number_of_included_mags": 5,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Chameleon Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-chameleon-threaded-barrel-black.html",
			"price": 349.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202183_21726_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-chameleon-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Non Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-non-threaded-barrel-flat-dark-earth.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202181_21726_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-non-threaded-barrel-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-black.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202182_21726_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-flat-dark-earth.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202180_21326_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-threaded-barrel-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW1 RMR Pistol With Copper Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-copper-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202125_2426_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-copper-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW1 RMR Pistol With Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-threaded-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202123_13026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel & 10-17rd Mags, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-10-17rd-mags-black.html",
			"price": 439.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202140_3926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-10-17rd-mags-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 10,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202126_2426_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-flat-dark-earth.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202127_2626_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202128_2626_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With TiN Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-tin-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202129_2626_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-tin-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Copper Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-copper-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202151_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-copper-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-flat-dark-earth2.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202163_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-flat-dark-earth2.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202162_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		}
	],
	"slide_colors": {
		"black": "Black",
		"sniper_green": "Sniper Green",
		"sniper_greencerakote": "Sniper GreenCerakote",
		"flat_dark_earth": "Flat Dark Earth",
		"black_cerkote": "Black Cerkote"
	},
	"frame_colors": {
		"black": "Black",
		"sniper_green": "Sniper Green",
		"flat_dark_earth": "Flat Dark Earth"
	}
} as const

export default data
