import type { DaggersData } from './product.d.ts'

const data: DaggersData = {
	"daggers": [
		{
			"psa_product_name": "PSA Dagger Compact 9mm Pistol with Extreme Carry Cuts,  Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-compact-9mm-pistol-with-extreme-carry-cuts-black-dlc.html",
			"price": 299.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/9/1/910115111_51024_1.jpg",
			"image_file_name": "psa-dagger-compact-9mm-pistol-with-extreme-carry-cuts-black-dlc.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "none",
			"mag_bag_bonus": false,
			"number_of_included_mags": 1,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW1 RMR Pistol, Threaded Barrel w/ 5 15rd & 5 27rd Mags, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-complete-sw1-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655210743_31926_1.jpg",
			"image_file_name": "psa-dagger-complete-sw1-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 5,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Compact SW3 RMR Pistol, Threaded Barrel w/ 5 15rd & 5 27rd Mags, FDE",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-complete-sw3-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg01-51655210744_31926_1.jpg",
			"image_file_name": "psa-dagger-complete-sw3-rmr-pistol-threaded-barrel-w-5-15rd-5-27rd-mags-fde.jpg",
			"size": "compact",
			"width": 1.28,
			"length": 7.15,
			"height": 4.78,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": null,
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 5,
			"mag_size": 15
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm ECC RMR Threaded Barrel Pistol, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-flat-dark-earth.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202121_13026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.15,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm ECC RMR Threaded Barrel Pistol, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-sniper-green.html",
			"price": 319.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202122_13026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-ecc-rmr-threaded-barrel-pistol-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.15,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol with SW1 RMR, Threaded Barrel & 5 17rd & 5 27rd Mags, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-sw1-rmr-threaded-barrel-5-15rd-5-17rd-mags-black.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655210745_31926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-sw1-rmr-threaded-barrel-5-15rd-5-17rd-mags-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black_cerkote",
			"slide_coating": "none",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 5,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol with SW2 RMR, Threaded Barrel & 5 17rd & 5 27rd Mags, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-sw2-rmr-threaded-barrel-5-15rd-5-17rd-mags-sniper-green.html",
			"price": 429.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655210746_31926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-sw2-rmr-threaded-barrel-5-15rd-5-17rd-mags-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": false,
			"number_of_included_mags": 5,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Chameleon Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-chameleon-threaded-barrel-black.html",
			"price": 349.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202183_21726_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-chameleon-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm Pistol With SWRV2 RMR Slide & Non Threaded Barrel, Flat Dark Earth",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-non-threaded-barrel-flat-dark-earth.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202181_21726_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-pistol-with-swrv2-rmr-slide-non-threaded-barrel-flat-dark-earth.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 3.9,
			"longer_barrel": false,
			"threaded_barrel": false,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "flat_dark_earth",
			"slide_coating": "cerakote",
			"frame_color": "flat_dark_earth",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW1 RMR Pistol With Copper Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-copper-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202125_2426_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-copper-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW1 RMR Pistol With Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-threaded-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202123_13026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw1-rmr-pistol-with-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel & 10-17rd Mags, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-10-17rd-mags-black.html",
			"price": 439.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202140_3926_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-10-17rd-mags-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 10,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With Threaded Barrel, Black",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-black.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202126_2426_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-threaded-barrel-black.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "black",
			"slide_coating": "cerakote",
			"frame_color": "black",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW2 RMR Pistol With TiN Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-tin-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202129_2626_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw2-rmr-pistol-with-tin-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Copper Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-copper-threaded-barrel-sniper-green.html",
			"price": 339.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202151_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-copper-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		},
		{
			"psa_product_name": "PSA Dagger Full Size - S 9mm SW3 RMR Pistol With Threaded Barrel, Sniper Green",
			"psa_url": "https://palmettostatearmory.com/psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-sniper-green.html",
			"price": 329.99,
			"original_product_image_url": "https://palmettostatearmory.com/media/catalog/product/cache/7af8331bf1196ca28793bd1e8f6ecc7b/d/g/dg02-51655202162_21026_1.jpg",
			"image_file_name": "psa-dagger-full-size-s-9mm-sw3-rmr-pistol-with-threaded-barrel-sniper-green.jpg",
			"size": "full_size_s",
			"width": 1.28,
			"length": 7.65,
			"height": 5.38,
			"barrel_length": 4.5,
			"longer_barrel": false,
			"threaded_barrel": true,
			"night_sight": false,
			"compensated_slide": false,
			"slide_color": "sniper_green",
			"slide_coating": "cerakote",
			"frame_color": "sniper_green",
			"optic_compatibility": "rmr",
			"mag_bag_bonus": true,
			"number_of_included_mags": 1,
			"mag_size": 17
		}
	],
	"slide_colors": {
		"black": "Black",
		"flat_dark_earth": "Flat Dark Earth",
		"sniper_green": "Sniper Green",
		"black_cerkote": "Black Cerkote"
	},
	"frame_colors": {
		"flat_dark_earth": "Flat Dark Earth",
		"sniper_green": "Sniper Green",
		"black": "Black"
	}
} as const

export default data
