export type Size = 'micro' | 'compact' | 'full_size_s'
export type SlideColor =
	| 'sniper_green'
	| 'black'
	| 'flat_dark_earth'
	| 'dlc_coating'
	| 'black_dlc'
export type FrameColor =
	| 'sniper_green'
	| 'black'
	| 'flat_dark_earth'
	| '2_tone'
	| 'two_tone'
	| 'm81_woodland_camo'
	| 'm81_desert_camo'
export type OpticCompatibility = 'none' | 'rmr' | 'shield_rmsc'
export type SlideFinish =
	| 'sniper_green'
	| 'black'
	| 'flat_dark_earth'
	| 'dlc_coating'
	| 'black_dlc'
export type FrameFinish =
	| 'sniper_green'
	| 'black'
	| 'flat_dark_earth'
	| '2_tone'
	| 'two_tone'
	| 'm81_woodland_camo'
	| 'm81_desert_camo'
export type OpticCompatibility = 'none' | 'rmr' | 'shield_rmsc'
